# === General Settings ===
general:
  plot_currents: true
  do_validation: true
  override_download: true


  start_date: "1993-01-01"
  end_date: "1993-01-03"
  override_current: true
  ssh_mode: 'cmems' #options: cmems, neurost
  do_eq: true


plot_currents:
  region: "global" #options: gulf_stream, indian_ocean, caribbean, global, austrailia_nz
  
#to do 
#update readme
#add currents_to_pdf ... ??
#ssh_file_gradient_not in folder 