# === General Settings ===
general:
  do_download: true
  do_currents: true
  plot_currents: true
  do_validation: true
 
  override_download: true


  start_date: "2012-01-01"
  end_date: "2012-01-01"
  override_current: true
  ssh_mode: 'cmems' #options: cmems, neurost,..error when "both".. fix that
  do_eq: true


plot_currents:
  region: "global" #options: gulfstream, indian ocean, caribbean, global, austrailia_nz
  
#note_to_self.. 
#neurost has data from 2010, currently cannont validate without neurost, wll fix that 